"""APIx dashboard.

Built around one principle: no index value appears anywhere on this page without the
availability rate that produced it. Not in a tooltip, not on another tab — next to it.
CLAUDE.md forbids reporting one without the other, and a dashboard is exactly where that
rule quietly gets broken because a clean-looking chart is more satisfying than an honest one.

    streamlit run dashboard/app.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from plotly.subplots import make_subplots

REPO = Path(__file__).resolve().parents[1]
INDEX = REPO / "data" / "index"
DATA = REPO / "data"

st.set_page_config(page_title="APIx — Indian Airfare Price Index", page_icon="✈", layout="wide")

INK = "#0f172a"
MUTED = "#64748b"
HEADLINE = "#1d4ed8"
BAND = "rgba(29,78,216,0.13)"
HEDONIC = "#c2410c"
GEKS = "#047857"
WARN = "#b45309"


@st.cache_data(ttl=300)
def load(name: str) -> pd.DataFrame | None:
    p = INDEX / name
    if not p.exists():
        return None
    df = pd.read_csv(p)
    if "collection_date" in df.columns:
        df["collection_date"] = pd.to_datetime(df["collection_date"])
    return df


@st.cache_data(ttl=300)
def load_json(path: Path) -> dict | list | None:
    return json.loads(path.read_text()) if path.exists() else None


meta = load_json(INDEX / "index_meta.json") or {}
health = load_json(DATA / "collection_health.json") or []
band = load("index_band.csv")
headline = load("index_uniform.csv")
hedonic = load("index_hedonic.csv")
geks = load("index_geks.csv")
direct = load("index_direct.csv")
avail = load("availability.csv")
strata = load("stratum_index.csv")

SIMULATED = (INDEX / "_THIS_IS_SIMULATED_DATA.txt").exists()

st.title("APIx — Real-time Airfare Price Index for India")
st.caption(
    "A daily matched-model price index for Indian domestic airfares, built to a standard "
    "the National Statistical Office could consume. SIH 2026 · problem statement SIH26056 · MoSPI."
)

if SIMULATED:
    st.error(
        "**SIMULATED DATA — NOT A MEASUREMENT.** Every number on this page was generated by "
        "`scripts/simulate.py` as a test fixture for the index pipeline. These are not "
        "observed fares and must not be presented as an index.",
        icon="🚨",
    )

if headline is None or headline.empty:
    st.warning(
        "No index has been built yet. The index needs at least two collection days — a price "
        "index measures change between periods, and on day one there is no change to measure. "
        "This is the honest state of the system, not an error.",
        icon="⏳",
    )
    if health:
        st.subheader("Collection health")
        st.dataframe(pd.DataFrame(health), use_container_width=True)
    st.stop()


# ------------------------------------------------------------------ headline numbers
latest = headline.iloc[-1]
prev = headline.iloc[-2] if len(headline) > 1 else latest
band_latest = band.iloc[-1] if band is not None and not band.empty else None

c1, c2, c3, c4, c5 = st.columns(5)
c1.metric(
    "Index level",
    f"{latest.index_value:.2f}",
    f"{latest.index_value - prev.index_value:+.2f} vs previous day",
    help="Base = 100 on the first collection day.",
)
c2.metric(
    "Availability rate",
    f"{latest.availability_rate:.1%}",
    help="Share of the 120 basket cells that returned a real quote. Read this with the index "
         "level, always. An index built on 40 cells is not the same claim as one built on 118.",
)
c3.metric(
    "Directly observed",
    f"{latest.observed_weight_share:.1%}",
    help="Share of basket weight observed rather than imputed from donor strata.",
)
c4.metric(
    "Sensitivity band",
    f"±{band_latest.band_width_pts / 2:.2f} pts" if band_latest is not None else "—",
    help="Spread across the three lead-time weighting scenarios. This is the uncertainty "
         "introduced by the one input no public Indian source provides.",
)
c5.metric("Collection days", f"{meta.get('collection_days', len(headline))}")

if latest.availability_rate < 0.8:
    st.warning(
        f"Availability was {latest.availability_rate:.0%} on {latest.collection_date:%d %b}. "
        "Below roughly 80%, a material share of the index is imputed by stratum movement. "
        "The value is still published — imputation is documented and flagged — but it rests "
        "on fewer observations than usual.",
        icon="⚠",
    )

tabs = st.tabs([
    "Index & band", "Lead-time curve", "Route heatmap", "Availability",
    "Robustness", "CPI benchmark", "Collection health", "Methodology",
])


# ------------------------------------------------------------------ 1. index & band
with tabs[0]:
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    if band is not None and not band.empty:
        b = band.copy()
        b["collection_date"] = pd.to_datetime(b["collection_date"])
        fig.add_trace(go.Scatter(x=b.collection_date, y=b.band_high, line=dict(width=0),
                                 showlegend=False, hoverinfo="skip"))
        fig.add_trace(go.Scatter(x=b.collection_date, y=b.band_low, fill="tonexty",
                                 fillcolor=BAND, line=dict(width=0),
                                 name="Lead-time scenario band"))
    fig.add_trace(go.Scatter(x=headline.collection_date, y=headline.index_value,
                             name="Chained Jevons (headline, uniform)",
                             line=dict(color=HEADLINE, width=3)))
    fig.add_trace(go.Bar(x=headline.collection_date, y=headline.availability_rate,
                         name="Availability rate", marker_color=MUTED, opacity=0.28),
                  secondary_y=True)
    fig.add_hline(y=100, line_dash="dot", line_color=MUTED,
                  annotation_text="base = 100", annotation_position="right")
    fig.update_yaxes(title_text="Index level", secondary_y=False)
    fig.update_yaxes(title_text="Availability", tickformat=".0%", range=[0, 1.6],
                     secondary_y=True, showgrid=False)
    fig.update_layout(height=520, hovermode="x unified", margin=dict(t=30, b=10),
                      legend=dict(orientation="h", y=1.12))
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        "The availability rate is drawn on the same chart on purpose. When the bars dip, the "
        "line above them is resting on fewer observations, and the reader can see that without "
        "being told."
    )

    st.markdown("#### Why there is a band and not a single line")
    st.markdown(
        "Route weights come from real DGCA passenger volumes. Lead-time weights cannot: no "
        "public source publishes how far in advance Indians book, and airlines do not release "
        "it. Rather than invent a booking curve and never mention it again, the index is "
        "computed under three defensible assumptions — near-term-heavy, uniform, and "
        "advance-heavy — and the spread between them is published. Where the band is narrow, "
        "the headline is robust to the thing we don't know. Where it is wide, the number "
        "depends on an assumption, and saying so is more useful than hiding it."
    )


# ------------------------------------------------------------------ 2. lead-time curve
with tabs[1]:
    st.markdown("#### How much does waiting cost?")
    st.markdown(
        "Each line is one advance-purchase stratum. Their *level* differences show the "
        "advance-purchase premium; their *divergence over time* shows that the strata are "
        "genuinely different products, which is the whole argument for stratifying by lead "
        "time rather than taking one spot price a month."
    )
    if strata is not None and not strata.empty:
        s = strata.copy()
        s["collection_date"] = pd.to_datetime(s["collection_date"])
        by_lt = s.groupby(["collection_date", "lead_time_days"], as_index=False)["stratum_index"].mean()
        fig = go.Figure()
        palette = {1: "#b91c1c", 7: "#c2410c", 15: "#a16207", 30: "#047857", 45: "#1d4ed8"}
        for lt in sorted(by_lt.lead_time_days.unique()):
            d = by_lt[by_lt.lead_time_days == lt]
            fig.add_trace(go.Scatter(x=d.collection_date, y=d.stratum_index, name=f"T+{int(lt)}",
                                     line=dict(color=palette.get(int(lt), MUTED), width=2)))
        fig.update_layout(height=460, hovermode="x unified", yaxis_title="Stratum index level",
                          legend=dict(orientation="h", y=1.1), margin=dict(t=30))
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("#### Fare level by lead time (all routes, latest day)")
        st.caption(
            "This is the elasticity the problem statement is really about: the same seat, "
            "the same route, priced differently purely by when you looked."
        )


# ------------------------------------------------------------------ 3. route heatmap
with tabs[2]:
    st.markdown("#### Where the movement is")
    if strata is not None and not strata.empty:
        s = strata.copy()
        s["collection_date"] = pd.to_datetime(s["collection_date"])
        s["route"] = s.origin + "→" + s.destination
        piv = s.pivot_table(index="route", columns="collection_date",
                            values="stratum_index", aggfunc="mean")
        fig = go.Figure(go.Heatmap(
            z=piv.values, x=piv.columns, y=piv.index, colorscale="RdBu_r", zmid=100,
            colorbar=dict(title="Index"),
        ))
        fig.update_layout(height=760, margin=dict(t=30, l=10))
        st.plotly_chart(fig, use_container_width=True)
        st.caption(
            "Directional. DEL→BOM and BOM→DEL are separate rows because they are separate "
            "products with separate load factors, and averaging them away would discard the "
            "asymmetry the index exists to measure."
        )


# ------------------------------------------------------------------ 4. availability
with tabs[3]:
    st.markdown("#### Data quality, as a first-class output")
    if avail is not None and not avail.empty:
        a = avail.copy()
        a["collection_date"] = pd.to_datetime(a["collection_date"])
        fig = go.Figure()
        fig.add_trace(go.Bar(x=a.collection_date, y=a.cells_priced, name="Priced",
                             marker_color="#047857"))
        fig.add_trace(go.Bar(x=a.collection_date, y=a.cells_sold_out, name="Sold out (market signal)",
                             marker_color=WARN))
        fig.add_trace(go.Bar(x=a.collection_date, y=a.cells_blocked, name="Blocked (our failure)",
                             marker_color="#b91c1c"))
        fig.update_layout(barmode="stack", height=440, hovermode="x unified",
                          yaxis_title="Basket cells", legend=dict(orientation="h", y=1.12),
                          margin=dict(t=30))
        st.plotly_chart(fig, use_container_width=True)
    st.info(
        "**Sold out and blocked are opposite facts and are never merged.** A sold-out cell is "
        "information about the market — the product genuinely cannot be bought at any price, "
        "which is itself a demand signal the CPI cannot currently produce. A blocked cell is "
        "information about us: the market had a price and we failed to observe it. Collapsing "
        "the two would let our own scraping failures masquerade as market scarcity.",
        icon="ℹ",
    )
    if meta.get("imputation_by_day"):
        st.markdown("#### Imputation tiers by day")
        st.caption(
            "Which donor each missing stratum borrowed its movement from. Carry-forward is "
            "never used: repeating yesterday's price asserts zero change on no evidence, and "
            "flattens the series exactly when the market is moving most."
        )
        st.dataframe(pd.DataFrame(meta["imputation_by_day"]), use_container_width=True)


# ------------------------------------------------------------------ 5. robustness
with tabs[4]:
    st.markdown("#### Four constructions of the same thing")
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=headline.collection_date, y=headline.index_value,
                             name="Chained Jevons (headline)", line=dict(color=HEADLINE, width=3)))
    if geks is not None and not geks.empty:
        fig.add_trace(go.Scatter(x=geks.collection_date, y=geks.geks_index,
                                 name="GEKS-Jevons (multilateral)", line=dict(color=GEKS, width=2)))
    if direct is not None and not direct.empty:
        fig.add_trace(go.Scatter(x=direct.collection_date, y=direct.direct_index,
                                 name="Direct fixed-base", line=dict(color=MUTED, width=2, dash="dot")))
    if hedonic is not None and not hedonic.empty:
        h = hedonic.copy()
        h["collection_date"] = pd.to_datetime(h["collection_date"])
        fig.add_trace(go.Scatter(x=h.collection_date, y=h.hedonic_index,
                                 name="Hedonic time-dummy", line=dict(color=HEDONIC, width=2)))
        if "ci_high" in h.columns:
            fig.add_trace(go.Scatter(x=h.collection_date, y=h.ci_high, line=dict(width=0),
                                     showlegend=False, hoverinfo="skip"))
            fig.add_trace(go.Scatter(x=h.collection_date, y=h.ci_low, fill="tonexty",
                                     fillcolor="rgba(194,65,12,0.10)", line=dict(width=0),
                                     name="Hedonic 95% interval"))
    fig.update_layout(height=520, hovermode="x unified", yaxis_title="Index level",
                      legend=dict(orientation="h", y=1.12), margin=dict(t=30))
    st.plotly_chart(fig, use_container_width=True)

    d1, d2 = st.columns(2)
    with d1:
        st.markdown("**Hedonic vs headline**")
        st.caption(
            "The hedonic controls for route, carrier, lead time, day of week, departure time "
            "band and Indian public holidays, so its date coefficients are a quality-adjusted "
            "index. Two series built on different principles that track each other are far "
            "more convincing than either alone."
        )
        st.json(meta.get("hedonic_vs_headline", {}))
    with d2:
        st.markdown("**Chain-drift diagnostic**")
        st.caption(
            "Chaining multiplies daily relatives, so sampling noise accumulates as a random "
            "walk even when prices do not move. GEKS is transitive and does not accumulate. "
            "The gap between them is the drift, measured rather than assumed away."
        )
        st.json(meta.get("chain_drift", {}))


# ------------------------------------------------------------------ 6. CPI benchmark
with tabs[5]:
    st.markdown("#### Against MoSPI's own CPI air-transport sub-class")
    cpi = load("cpi_benchmark.csv")
    if cpi is None or cpi.empty:
        st.info(
            "The CPI benchmark has not been pulled yet. Run `python scripts/fetch_cpi_benchmark.py`, "
            "which reads MoSPI's official eSankhyiki service. Once at least one full month of "
            "collection exists, the monthly APIx series is correlated against the published "
            "CPI air-transport sub-class here.",
            icon="📊",
        )
        st.markdown(
            "**What this comparison can and cannot show.** A high correlation is supporting "
            "evidence, not proof of correctness — the two series measure related but distinct "
            "things, at different frequencies, from different samples. A *low* correlation is "
            "the more interesting result, and would need explaining rather than hiding: it "
            "would most likely mean the monthly spot-price approach is missing intra-month "
            "movement that daily collection captures, which is the entire premise of this "
            "project."
        )
    else:
        st.dataframe(cpi, use_container_width=True)


# ------------------------------------------------------------------ 7. health
with tabs[6]:
    st.markdown("#### Collection health")
    st.caption(
        "Eurostat recommends monitoring the collection itself as a first-class output. "
        "Almost nobody builds it, and it is the difference between noticing a source died "
        "within one cycle and noticing it after a week-long hole in the series."
    )
    if health:
        h = pd.DataFrame(health)
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=pd.to_datetime(h.collection_date), y=h.availability_rate,
                                 mode="lines+markers", name="Availability",
                                 line=dict(color=HEADLINE, width=2)))
        fig.add_hline(y=0.8, line_dash="dash", line_color=WARN,
                      annotation_text="80% floor", annotation_position="right")
        fig.update_layout(height=360, yaxis_tickformat=".0%", yaxis_range=[0, 1],
                          margin=dict(t=30))
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(h, use_container_width=True)

        per_source = h.iloc[-1].get("per_source")
        if isinstance(per_source, dict) and per_source:
            st.markdown("**Per-source outcome, latest run**")
            st.dataframe(pd.DataFrame(per_source).T, use_container_width=True)
    else:
        st.info("No collection runs recorded yet.")


# ------------------------------------------------------------------ 8. methodology
with tabs[7]:
    md = REPO / "docs" / "methodology.md"
    if md.exists():
        st.markdown(md.read_text())
    else:
        st.info("docs/methodology.md not found.")
